// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetItemsItemsGetResponse, CreateItemItemsPostData, CreateItemItemsPostResponse } from './types.gen';

export class DefaultService {
    /**
     * Get Items
     * @returns Item Successful Response
     * @throws ApiError
     */
    public static getItemsItemsGet(): CancelablePromise<GetItemsItemsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/items/'
        });
    }
    
    /**
     * Create Item
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ResponseMessage Successful Response
     * @throws ApiError
     */
    public static createItemItemsPost(data: CreateItemItemsPostData): CancelablePromise<CreateItemItemsPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}